INSERT INTO roles (id, name, description, created_at, updated_at)
VALUES
    (gen_random_uuid(),'CUSTOMER','DEFAULT CUSTOMER ROLE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
    (gen_random_uuid(),'ADMIN','SYSTEM ADMINISTRATOR ROLE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
    (gen_random_uuid(),'EMPLOYEE','DEFAULT EMPOLYEE ROLE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT (name) DO NOTHING;